export const CHANGE_LANG = 'App/CHANGE_LANG';
export const LOAD_CONFIG_REQUEST = 'App/LOAD_CONFIG_REQUEST';
export const SIGN_IN = 'User/SIGN_IN';
export const SIGN_OUT = 'User/SIGN_OUT';
export const UPDATE_PROFILE_SUCCESS = 'User/UPDATE_PROFILE_SUCCESS';
export const LOAD_AUTH = 'User/LOAD_AUTH';
export const LOAD_CONFIG_SUCCESS = 'App/LOAD_CONFIG_SUCCESS';
export const LOAD_CONFIG_FAILURE = 'App/LOAD_CONFIG_FAILURE';